### 前台 && 管理員註冊
POST http://localhost:3000/api/v2/admin/signup
Content-Type: application/json

{
  "email": "root@gmail.com",
  "password": "jmaker00643",
  "nickname": "root"
}

### 前台 && 管理員登入
POST http://localhost:3000/api/v2/admin/login
Content-Type: application/json

{
  "email": "root@gmail.com",
  "password": "jmaker00643"
}

### 前台 && 檢查是否持續登入
POST http://localhost:3000/api/v2/admin/check

### 前台 && 管理員登出
POST http://localhost:3000/api/v2/admin/logout
