### 管理員註冊
POST http://localhost:3000/api/v2/admin/
Content-Type: application/json

{
  "email": "root@gmail.com",
  "password": "jmaker00643"
}

### 管理員登入
POST http://localhost:3000/api/v2/admin/login
Content-Type: application/json

{
  "email": "root@gmail.com",
  "password": "jmaker00643"
}

###

GET http://localhost:3000/api/v2/admin
