@BASE_URL = http://localhost:3000/api/v2
# @BASE_URL = https://jmaker-ac.vercel.app/api/v2

### 加入用戶
POST {{BASE_URL}}/users
Content-Type: application/json

{
  "id": "d9685f2e4d"
}

### 權限檢查
GET {{BASE_URL}}/users/001/auth

### 取得所有用戶
GET {{BASE_URL}}/users

### 取得指定用戶
GET {{BASE_URL}}/users/4A6G0067

### 刪除指定用戶
DELETE {{BASE_URL}}/users/002

### 實體用戶註冊
PATCH {{BASE_URL}}/users/002
Content-Type: application/json

{
  "username": "弘毅全",
  "userid": "4A6G0067"
}

### 調整訪問權限
PATCH {{BASE_URL}}/users/002/auth
Content-Type: application/json

{
  "auth": false
}
